import { defineSchema } from "@/core/settings-engine/schema";

const vizOn = (v: Record<string, unknown>) => v.vizEnabled !== false;

export const musicFxSettingsSchema = defineSchema({
  vizEnabled: {
    type: "toggle",
    label: "musicFx.vizEnabled",
    description: "musicFx.vizEnabledDesc",
    default: true,
  },
  // read by the popup's Audio Mixer (by feature id — features don't import each other)
  autoCapture: {
    type: "toggle",
    label: "musicFx.autoCapture",
    description: "musicFx.autoCaptureDesc",
    default: true,
  },
  vizMode: {
    type: "select",
    label: "musicFx.mode",
    options: [
      { value: "bars", label: "musicFx.modeBars" },
      { value: "mirror", label: "musicFx.modeMirror" },
      { value: "wave", label: "musicFx.modeWave" },
      { value: "glow", label: "musicFx.modeGlow" },
      { value: "circle", label: "musicFx.modeCircle" },
      { value: "dots", label: "musicFx.modeDots" },
    ],
    default: "bars",
    showIf: vizOn,
  },
  vizPosition: {
    type: "select",
    label: "musicFx.position",
    options: [
      { value: "bottom", label: "musicFx.posBottom" },
      { value: "top", label: "musicFx.posTop" },
      { value: "center", label: "musicFx.posCenter" },
      { value: "full", label: "musicFx.posFull" },
    ],
    default: "bottom",
    showIf: vizOn,
  },
  vizLayer: {
    type: "select",
    label: "musicFx.layer",
    description: "musicFx.layerDesc",
    options: [
      { value: "above", label: "musicFx.layerAbove" },
      { value: "behind", label: "musicFx.layerBehind" },
    ],
    default: "above",
    showIf: vizOn,
  },
  vizColor: {
    type: "select",
    label: "musicFx.color",
    options: [
      { value: "accent", label: "musicFx.colorAccent" },
      { value: "rainbow", label: "musicFx.colorRainbow" },
      { value: "custom", label: "musicFx.colorCustom" },
    ],
    default: "accent",
    showIf: vizOn,
  },
  vizColor1: {
    type: "color",
    label: "musicFx.color1",
    default: "#38bdf8",
    showIf: (v) => vizOn(v) && v.vizColor === "custom",
  },
  vizColor2: {
    type: "color",
    label: "musicFx.color2",
    default: "#c084fc",
    showIf: (v) => vizOn(v) && v.vizColor === "custom",
  },
  vizBars: {
    type: "slider",
    label: "musicFx.bars",
    min: 16,
    max: 128,
    step: 8,
    default: 64,
    showIf: vizOn,
  },
  vizHeight: {
    type: "slider",
    label: "musicFx.height",
    min: 40,
    max: 400,
    step: 10,
    default: 140,
    showIf: vizOn,
  },
  vizOpacity: {
    type: "slider",
    label: "musicFx.opacity",
    min: 10,
    max: 100,
    step: 5,
    default: 80,
    showIf: vizOn,
  },
  vizSensitivity: {
    type: "slider",
    label: "musicFx.sensitivity",
    min: 50,
    max: 200,
    step: 10,
    default: 100,
    showIf: vizOn,
  },
  pulseEnabled: {
    type: "toggle",
    label: "musicFx.pulseEnabled",
    description: "musicFx.pulseEnabledDesc",
    default: true,
  },
  pulseStrength: {
    type: "slider",
    label: "musicFx.pulseStrength",
    min: 1,
    max: 10,
    step: 1,
    default: 5,
    showIf: (v) => v.pulseEnabled !== false,
  },
  pulseStyle: {
    type: "select",
    label: "musicFx.pulseStyle",
    description: "musicFx.pulseStyleDesc",
    options: [
      { value: "even", label: "musicFx.pulseEven" },
      { value: "dynamic", label: "musicFx.pulseDynamic" },
    ],
    default: "even",
    showIf: (v) => v.pulseEnabled !== false,
  },
  pulseDensity: {
    type: "select",
    label: "musicFx.pulseDensity",
    description: "musicFx.pulseDensityDesc",
    options: [
      { value: "normal", label: "musicFx.densityNormal" },
      { value: "dense", label: "musicFx.densityDense" },
    ],
    default: "normal",
    showIf: (v) => v.pulseEnabled !== false,
  },
  pulseSensitivity: {
    type: "slider",
    label: "musicFx.pulseSensitivity",
    description: "musicFx.pulseSensitivityDesc",
    min: 1,
    max: 10,
    step: 1,
    default: 5,
    showIf: (v) => v.pulseEnabled !== false,
  },
});
